import React, { Suspense, useState } from 'react'
import { Routes, Route } from 'react-router-dom'
import Sidebar from './components/Sidebar.jsx'
import HomePage from './pages/HomePage.jsx'
import AppShell from './components/AppShell.jsx'
import IframeShell from './components/IframeShell.jsx'
import LoadingScreen from './components/LoadingScreen.jsx'
import NotFound from './pages/NotFound.jsx'

// Auto-generated by scripts/generate.js
import { routeConfig } from '../generated/routes.js'

export default function App() {
  const [sidebarOpen, setSidebarOpen] = useState(true)

  return (
    <div className="flex h-screen bg-surface-0 overflow-hidden">
      <Sidebar isOpen={sidebarOpen} onToggle={() => setSidebarOpen(p => !p)} />

      <main className="flex-1 overflow-y-auto">
        <Suspense fallback={<LoadingScreen />}>
          <Routes>
            <Route path="/" element={<HomePage />} />

            {routeConfig.map((route) => {
              const { path, slug, name, type, component: Component, htmlPath, url, iframeOptions } = route

              // ── react: wrap in AppShell, render lazy component ──
              if (type === 'react') {
                return (
                  <Route
                    key={slug}
                    path={path}
                    element={
                      <AppShell name={name} slug={slug} type={type}>
                        <Component />
                      </AppShell>
                    }
                  />
                )
              }

              // ── html: AppShell breadcrumb + IframeShell pointing to static file ──
              if (type === 'html') {
                return (
                  <Route
                    key={slug}
                    path={path}
                    element={
                      <AppShell name={name} slug={slug} type={type} noPadding>
                        <IframeShell
                          src={htmlPath}
                          name={name}
                          type="html"
                          options={iframeOptions}
                        />
                      </AppShell>
                    }
                  />
                )
              }

              // ── url: AppShell breadcrumb + IframeShell pointing to external URL ──
              if (type === 'url') {
                return (
                  <Route
                    key={slug}
                    path={path}
                    element={
                      <AppShell name={name} slug={slug} type={type} noPadding>
                        <IframeShell
                          src={url}
                          name={name}
                          type="url"
                          options={iframeOptions}
                        />
                      </AppShell>
                    }
                  />
                )
              }

              return null
            })}

            <Route path="*" element={<NotFound />} />
          </Routes>
        </Suspense>
      </main>
    </div>
  )
}
