import React, { Suspense, useState } from 'react'
import { Routes, Route } from 'react-router-dom'
import Sidebar from './components/Sidebar.jsx'
import HomePage from './pages/HomePage.jsx'
import AppShell from './components/AppShell.jsx'
import LoadingScreen from './components/LoadingScreen.jsx'
import NotFound from './pages/NotFound.jsx'

// Auto-generated by scripts/generate.js
// If this import fails, run: node scripts/generate.js
import { routeConfig } from '../generated/routes.js'

export default function App() {
  const [sidebarOpen, setSidebarOpen] = useState(true)

  return (
    <div className="flex h-screen bg-surface-0 overflow-hidden">
      {/* Sidebar: auto-populated from generated navigation */}
      <Sidebar isOpen={sidebarOpen} onToggle={() => setSidebarOpen(p => !p)} />

      {/* Main content area */}
      <main
        className="flex-1 overflow-y-auto transition-all duration-300"
        style={{ marginLeft: sidebarOpen ? 0 : 0 }}
      >
        <Suspense fallback={<LoadingScreen />}>
          <Routes>
            {/* Homepage dashboard */}
            <Route path="/" element={<HomePage />} />

            {/* Auto-generated app routes */}
            {routeConfig.map(({ path, slug, name, component: Component }) => (
              <Route
                key={slug}
                path={path}
                element={
                  <AppShell name={name} slug={slug}>
                    <Component />
                  </AppShell>
                }
              />
            ))}

            {/* Fallback */}
            <Route path="*" element={<NotFound />} />
          </Routes>
        </Suspense>
      </main>
    </div>
  )
}
